
name: "e-com"
services:
  db:
    image: postgres
    env_file:
      - .env
    networks:
      - e-com
    ports:
      - 5432:5432
  # app:
  #   build:
  #     context: .
  #   image: nnd/e-com:latest
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   networks:
  #     - e-com


volumes:
  e-com-db:
    name: e-com-db

networks:
  e-com:
    name: e-com
